name: Towers
author: GhostCode
version: 1.1
description: The Towers MiniGame
main: dev.ghosty.towers.Towers
commands:
#  tptoworld:
#    permission: admin
#  editgame:
#    permission: towers.admin
  join:
    description: Join a game of Towers